# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  gplus_key: '934220560833-sj07qg7p7hl6nk84hp6apguj9idbin8i.apps.googleusercontent.com'
  gplus_secret: 'xvLXASh-q95k1MUb3wN6y5zU'
  facebook_key: '1287307147950050'
  facebook_secret: '8ac4c26320740b9f201a358169cbd0f0'
  vk_key: '5414114'
  vk_secret: 'oox62tsNeLHpTJbAtkbS'
  secret_key_base: 0e30b0c96620ae41bd68a4b536bf2a6b9075465e3a3e89bc4261a784fa580f0344d0694c1823a7aedaa4a3beb3e3ca36f16e549a126cdd81f021f9f64782733d

test:
  secret_key_base: beeb36376145e0d7bd95ee77c97b17180894e32071c569345d081623bb383adcc7d957084046d2d8d9fa40305c2d25c0358cd4b93b6b5799c3d9f9d12a303b8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
